#Q1. Display all movies
SELECT * FROM movie_rating;

#Q2. Show only movie title and genre
SELECT Title, Genre
FROM movie_rating;

#Q3. Find movies with ratings above 8
SELECT Title, Rating
FROM movie_rating
WHERE rating > 8;

#Q4. Find movies released after 2015
SELECT Title, Year
FROM movie_rating
WHERE Year > 2015;

#Q5.  Find the average movie rating
SELECT AVG(Rating) AS Average_Rating
FROM movie_rating;

#Q6.  Find the highest-rated movie
SELECT Title, Rating
FROM movie_rating
ORDER BY Rating Desc
LIMIT 1;

#Q7. Average rating by genre
SELECT Genre,
ROUND(AVG(Rating),2) AS Avg_Rating
FROM movie_rating
GROUP BY Genre
ORDER BY Avg_Rating DESC;

#Q8. Total revenue generated by each genre
SELECT Genre,
ROUND(SUM(Revenue),2) AS Total_Revenue
FROM movie_rating
GROUP BY Genre
ORDER BY Total_Revenue DESC;

#Q9. Top 10 movies by revenue
SELECT Title, Revenue
FROM movie_rating
ORDER BY Revenue DESC
LIMIT 10;

#Q10. Average rating by country
SELECT Country,
ROUND(AVG(Rating),2) AS Avg_Rating
FROM movie_rating
GROUP BY Country
ORDER BY Avg_Rating DESC;

#11. Movies with more than 50,000 votes
SELECT Title, Votes
FROM movie_rating
WHERE Votes > 50000
ORDER BY Votes DESC;

#12.  Count the number of unique countries
SELECT COUNT(DISTINCT Country) AS Total_Countries
FROM movie_rating;

#13. Rank movies by revenue
SELECT Title,Revenue,
RANK() OVER(ORDER BY Revenue DESC) AS Revenue_Rank
FROM movie_rating;

#14. Top 5 genres by average revenue
SELECT Genre,
ROUND(AVG(Revenue),2) AS Avg_Revenue
FROM movie_rating
GROUP BY Genre
ORDER BY Avg_Revenue DESC
LIMIT 5;

#15. Calculate average rating for each genre
SELECT Genre,
ROUND(AVG(Rating), 2) AS Average_Rating
FROM Movie_Rating
GROUP BY Genre
ORDER BY Average_Rating DESC;

#16. Find countries with their maximum movie revenue
SELECT Country,MAX(Revenue) AS Max_Revenue
FROM movie_rating
GROUP BY Country
ORDER BY Max_Revenue DESC;

#17. Find the year with the latest movie release
SELECT MAX(Year) AS Latest_Year
FROM movie_rating;

#18. Find countries with an average movie rating above 5
SELECT Country, AVG(Rating) AS Avg_Rating
FROM movie_rating
GROUP BY Country
HAVING AVG(Rating) > 5;

#19. Count the number of unique genres in the dataset
SELECT COUNT(DISTINCT Genre) AS Total_Genres
FROM movie_rating;

#20. Find all unique countries that produced movies
SELECT DISTINCT Country
FROM movie_rating
ORDER BY Country;











